language: java
jdk:
  - oraclejdk11
# Use a Build Matrix for subdirs (https://lord.io/blog/2014/travis-multiple-subdirs/)
env:
  - DIR=adminSDK/alertcenter/quickstart
  - DIR=adminSDK/directory/quickstart
  - DIR=adminSDK/reports/quickstart
  - DIR=adminSDK/reseller/quickstart
  - DIR=appsScript/quickstart
  - DIR=classroom/quickstart
  - DIR=drive/quickstart
  - DIR=gmail/quickstart
  - DIR=sheets/quickstart
  - DIR=slides/quickstart
  - DIR=tasks/quickstart
script: cd $DIR && gradle build # gradle -q run
